In [8]:
word='oxygen'
#word='the'

In [9]:
print(word[0])
print(word[1])
print(word[4])

o
x
e


In [13]:
word='the'
for char in word:
    print(char)

t
h
e


In [17]:
for i in range(5,10,2):
    print(i)

5
7
9


In [18]:
5**3

125

In [20]:
result=1
exponential=3
x=5
for number in range (0,exponential):
    result=result*x
print(result)

125


In [22]:
mylist=[1,3,5,7]
print(mylist)

[1, 3, 5, 7]


In [23]:
mylist[-1]

7

In [24]:
for i in mylist:
    print(i)

1
3
5
7


In [32]:
names=['Maria','Alice','James']

In [33]:
names

['Maria', 'Alice', 'James']

In [34]:
names[0]='Jake'

names

In [29]:
names

['Jake', 'Alice', 'James']

In [35]:
name='Jake'

In [36]:
name[0]='U'

TypeError: 'str' object does not support item assignment

In [37]:
names

['Jake', 'Alice', 'James']

In [38]:
name='Maria'

In [39]:
name

'Maria'

In [48]:
x=[1,2,3]

In [49]:
y=list(x)

In [50]:
y

[1, 2, 3]

In [51]:
x[0]='Darwin'

In [52]:
x

['Darwin', 2, 3]

In [53]:
y

[1, 2, 3]

In [54]:
x=['Darwin',1,3.0]

In [55]:
x=[['pepper','onion'],['bread','pasta'],['apple']]

In [57]:
x[0][1]

'onion'

In [58]:
x=[['a','b'],1,2]

y=x
z=list(x)

In [59]:
x[0][0]='A'

In [60]:
x

[['A', 'b'], 1, 2]

In [61]:
y

[['A', 'b'], 1, 2]

In [62]:
x[1]=5

In [63]:
x

[['A', 'b'], 5, 2]

In [64]:
y

[['A', 'b'], 5, 2]

In [65]:
z

[['A', 'b'], 1, 2]

In [66]:
x.append(12)

In [67]:
x

[['A', 'b'], 5, 2, 12]

In [68]:
x.pop(0)

['A', 'b']

In [69]:
x

[5, 2, 12]

In [70]:
x.reverse()

In [71]:
x

[12, 2, 5]

In [72]:
x[0:2]

[12, 2]

In [73]:
x[:2]

[12, 2]

In [74]:
x[1:]

[2, 5]

In [75]:
x=[1,2,4,6,6]

In [76]:
x[0:4:2]

[1, 4]

In [77]:
x
y

[12, 2, 5]

In [78]:
x

[1, 2, 4, 6, 6]

In [79]:
y

[12, 2, 5]

In [80]:
x+y

[1, 2, 4, 6, 6, 12, 2, 5]

In [81]:
x*2

[1, 2, 4, 6, 6, 1, 2, 4, 6, 6]

In [91]:
string_for_slicing='Observation date: 25.2.2021'
list_for_slicing=[['fluorine','F'],['chlorine','Cl'],['bromine','Br'],['iodine','I'],['astatine','At']]

In [92]:
print(string_for_slicing[-4:])
print(list_for_slicing[-4:])


2021
[['chlorine', 'Cl'], ['bromine', 'Br'], ['iodine', 'I'], ['astatine', 'At']]


In [94]:
num=37
if num<100 and num>0:
    print('number between 0 and 100')
elif num>100 or num <0:
    print('the number is greater than 100 or less than 0')
else:
    print('the number is not greater than 100')


number between 0 and 100


In [95]:
import numpy as np


In [97]:
data=np.loadtxt(fname='data/inflammation-01.csv',delimiter=',')

In [98]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [99]:
data.shape

(60, 40)

In [103]:
data[:,4].shape

(60,)

In [106]:
np.max(data,axis=0).shape

(40,)

In [109]:
max_inflammation_0=np.max(data,axis=0)[0]
print(max_inflammation_0)
max_inflammation_20=np.max(data,axis=0)[20]
print(max_inflammation_20)

0.0
20.0


In [112]:
if np.sum(np.min(data,axis=0))==0:
    print('Minima sum to zero')
elif max_inflammation_0==0 and max_inflammation_20==20:
    print('Check required')
else:
    print('Data look ok')

Check required


In [115]:
mylist=[]

if not mylist:
    print('mylist is False')

mylist is False


In [116]:
x=23
x+=1
print(x)
x*=4
print(x)

24
96


In [117]:
'inflammation-01.csv'.startswith('inflamm')

True

In [127]:
filenames=['inflammation-01.csv','inflammation-02.csv',
         'inflammation-03.csv','inflammation-04.csv','small-01.csv',
         'small-02.csv','src.py']

inflammation_data=[]
small_data=[]
other_data=[]

for myfile in filenames:
    if myfile.startswith('inflamm'):
        inflammation_data.append(myfile)
    elif myfile.startswith('small'):
        small_data.append(myfile)
    else:
        other_data.append(myfile)

print(inflammation_data)
print(small_data)
print(other_data)

['inflammation-01.csv', 'inflammation-02.csv', 'inflammation-03.csv', 'inflammation-04.csv']
['small-01.csv', 'small-02.csv']
['src.py']


In [151]:
def fahr_to_celsius(temp,temp2=0.0):
    '''
    Convert temp in f to c.
    :param temp: float, a temp in f
    '''
    temp_celsius=((temp-32)*(5/9))
    print(temp2)
    return temp_celsius

def celsius_to_kelvin(temp_c):
    temp_k=temp_c+273.15
    return temp_k

def fahr_to_kelvin(temp_f):
    temp_c=fahr_to_celsius(temp_f)
    temp_k=celsius_to_kelvin(temp_c)
    return temp_k
    

In [152]:
fahr_to_celsius(212,temp2=30)

30


100.0

In [140]:
celsius_to_kelvin(0.)

273.15

In [141]:
def sanity_check(data):
    max_inflammation_0=np.max(data,axis=0)[0]
    
    max_inflammation_20=np.max(data,axis=0)[20]
    
    if np.sum(np.min(data,axis=0))==0:
        print('Minima sum to zero')
    elif max_inflammation_0==0 and max_inflammation_20==20:
        print('Check required')
    else:
        print('Data look ok')
    

In [154]:
help (fahr_to_celsius)

Help on function fahr_to_celsius in module __main__:

fahr_to_celsius(temp, temp2=0.0)
    Convert temp in f to c.
    :param temp: float, a temp in f



In [156]:
data.shape


(60, 40)

In [157]:
def offset_mean(data,target_mean_value):
    return(data-np.mean(data))+target_mean_value

In [158]:
offset_mean(data,2.0)

array([[-4.14875, -4.14875, -3.14875, ..., -1.14875, -4.14875, -4.14875],
       [-4.14875, -3.14875, -2.14875, ..., -3.14875, -4.14875, -3.14875],
       [-4.14875, -3.14875, -3.14875, ..., -2.14875, -3.14875, -3.14875],
       ...,
       [-4.14875, -3.14875, -3.14875, ..., -3.14875, -3.14875, -3.14875],
       [-4.14875, -4.14875, -4.14875, ..., -4.14875, -2.14875, -4.14875],
       [-4.14875, -4.14875, -3.14875, ..., -3.14875, -3.14875, -4.14875]])

In [159]:
test_data=np.zeros((3,3))

In [160]:
test_data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [161]:
offset_mean(test_data,3)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [170]:
def test_offset_mean(target_value):
    test_data=np.zeros((3,3))
    
    mydata=offset_mean(test_data,target_value)
    
    assert mydata[0,0]==target_value

In [171]:
test_offset_mean(4)

In [173]:
def favourite_ice_cream():
    ice_cream=['vanilla','chocolate','lemon']
    print(ice_cream[3])

favourite_ice_cream()

IndexError: list index out of range

In [178]:
def some_function():
    message='hello'
    print (message)
    return message

In [179]:
greetings='hello'

In [180]:
gretings

NameError: name 'gretings' is not defined

In [182]:
count=0
for number in range (10):
    count=count+number

print('Count',count)

Count 45


In [183]:
numbers=[1,2,3,4]

In [184]:
numbers[7]

IndexError: list index out of range

In [187]:
data=np.loadtxt(fname='data/inflammation-01.csv',delimiter=',')

In [189]:
%%writefile myfile.txt
'Hello'

Writing myfile.txt


In [198]:
myfile=open('myfile.txt','r')
hello=myfile.read()

In [199]:
hello

''

In [203]:
mylist=[1,3,4]
mylist[0]='Darwin'

mylist

['Darwin', 3, 4]

In [210]:
mytuple=(1,3,4)

mytuple[-1]
mytuple[1]='Darwin'

TypeError: 'tuple' object does not support item assignment

In [212]:
mydict={'one':'monday',
       'two':'tuesday'}
mydict['one']

'monday'

In [216]:
mydict.items()

dict_items([('one', 'monday'), ('two', 'tuesday')])

In [218]:
def print_message(day):
    messages={'monday':'today is monday',
             'tuesday': 'finally tuesday',
             'wednesday':'today is wednesday',
             'thursday':'almost at the end'}
    print(messages[day])
    
def print_monday_message():
    print_message('monday')

print_monday_message()    

today is monday


In [222]:
x=1.2

import math


assert np.isclose(x,1.234), 'x is not zero'

AssertionError: x is not zero

In [ ]:
def is_overlapping(rect1,rect2):
    """
    Checks that two rectangles are overlapping
    
    :params rect: coordinates of the first rectangle
    :params rect2: coordinates of the second rectangle
    
    """

    